Controllers/CategoryController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication.Data;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private ComponentDbContext context;

        public CategoryController(ComponentDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            var categories = context.Categories.Include(c => c.CategoryComponentTypes).ToList();
            return View(categories);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(string categoryName)
        {
            if (!string.IsNullOrEmpty(categoryName))
            {
                var cat = new Category();
                cat.Name = categoryName;

                context.Categories.Add(cat);
                context.SaveChanges(true);

                return RedirectToAction("Show", new {id = cat.CategoryId});
            }
            else
            {
                ViewData["error"] = "Please input a correct name you noob.";
                return View();
            }
        }

        public IActionResult Show(int id)
        {
            var category = findCategoryById(id, true);

            return View(category);
        }

        public IActionResult Delete(int id)
        {
            ViewData["id"] = id;
            return View();
        }

        [ActionName("Delete")]
        [HttpPost]
        public IActionResult Delete_Category(int id)
        {
            var cat = findCategoryById(id);
            context.Categories.Remove(cat);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            var model = findCategoryById(id);
            return View(model);
        }

        [ActionName("Update")]
        [HttpPost]
        public IActionResult Update(int id, string categoryName)
        {
            var model = findCategoryById(id);
            model.Name = categoryName;
            context.Categories.Update(model);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult ComponentType(int id)
        {
            var categoryComponentTypes = context.Categories.Where(c => c.CategoryId == id)
                .Include(c => c.CategoryComponentTypes)
                .ThenInclude(cct => cct.ComponentType)
                .ToList();
            var model = context.ComponentTypes.Include(ct => ct.CategoryComponentTypes)
                .ThenInclude(cct => cct.Category)
                .Where(ct => ct.CategoryComponentTypes.All(cct => cct.CategoryId != id))
                .ToList();
            ViewData["id"] = id;
            return View(model);
        }

        [HttpPost]
        public IActionResult ComponentType(int id, int componentTypeId)
        {
            if (componentTypeId < 1)
            {
                return RedirectToAction("Show", new {id = id});
            }

            var category = findCategoryById(id, true);
            category.CategoryComponentTypes.Add(new CategoryComponentType
            {
                CategoryId = id,
                ComponentTypeId = componentTypeId
            });
            context.SaveChanges();
            return RedirectToAction("Show", new {id = id});
        }

        private Category findCategoryById(int id, bool includeTypes = false)
        {
            if (includeTypes)
            {
                return context.Categories.Include(c => c.CategoryComponentTypes)
                    .ThenInclude(cct => cct.ComponentType)
                    .Single(c => c.CategoryId == id);
            }
            else
            {
                return context.Categories.Single(c => c.CategoryId == id);
            }
        }
    }
}

Controllers/ComponentTypeController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using WebApplication.Data;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    [Authorize]
    public class ComponentTypeController : Controller
    {
        private ComponentDbContext context;

        public ComponentTypeController(ComponentDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            var componentTypes = context.ComponentTypes.Include(ct => ct.Components).ToList();
            return View(componentTypes);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(string ctName, string ctInfo, string ctLocation, ComponentTypeStatus ctStatus,
            string ctDatasheet, string ctImageUrl, string ctManufacturer, string ctWikiLink, string ctAdminComment)
        {
            if (!string.IsNullOrEmpty(ctName))
            {
                var coType = new ComponentType();
                coType.ComponentName = ctName;
                coType.ComponentInfo = ctInfo;
                coType.Location = ctLocation;
                coType.Status = ctStatus;
                coType.Datasheet = ctDatasheet;
                coType.ImageUrl = ctImageUrl;
                coType.Manufacturer = ctManufacturer;
                coType.WikiLink = ctWikiLink;
                coType.AdminComment = ctAdminComment;

                context.ComponentTypes.Add(coType);
                context.SaveChanges(true);

                return RedirectToAction("Show", new {id = coType.ComponentTypeId});
            }
            else
            {
                ViewData["error"] = "Please input a correct name.";
                return View();
            }
        }

        public IActionResult Show(int id)
        {
            var componentType =
                context.ComponentTypes.Include(ct => ct.CategoryComponentTypes)
                    .ThenInclude(cct => cct.Category)
                    .Include(ct => ct.Components)
                    .Single(ct => ct.ComponentTypeId == id);

            return View(componentType);
        }

        public IActionResult Delete(int id)
        {
            ViewData["id"] = id;
            return View();
        }

        [ActionName("Delete")]
        [HttpPost]
        public IActionResult Delete_ComponentType(int id)
        {
            var coType = findComponentTypeById(id);
            context.ComponentTypes.Remove(coType);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        private ComponentType findComponentTypeById(int id)
        {
            return context.ComponentTypes.Single(ct => ct.ComponentTypeId == id);
        }
    }
}

Controllers/SearchController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApplication.Data;

namespace WebApplication.Controllers
{
    [Authorize]
    public class SearchController : Controller
    {
        private ComponentDbContext context;

        public SearchController(ComponentDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Show(string query)
        {
            var model = context.ComponentTypes.Where(ct => ct.ComponentName.Contains(query)).ToList();

            return View(model);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>@ViewData["Title"] - EmbeddedStock</title>

  <environment names="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
  </environment>
  <environment names="Staging,Production">
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
  </environment>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">EmbeddedStock Admin</span>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
          <a asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="dropdown">
          <a asp-controller="Category" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a asp-controller="Category" asp-action="Index">Show categories</a>
            <li>
              <a asp-controller="Category" asp-action="Create">New category</a>
            </li>
          </ul>
        </li>
        <li class="dropdown">
          <a asp-controller="ComponentType" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ComponentType <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a asp-controller="ComponentType" asp-action="Index">Show ComponentTypes</a>
            <li>
              <a asp-controller="ComponentType" asp-action="Create">New ComponentType</a>
            </li>
          </ul>
        </li>
        <li>
          <a asp-controller="Search" asp-action="Index">Component search</a>
        </li>
      </ul>
      @await Html.PartialAsync("_LoginPartial")
    </div>
  </div>
</div>
<div class="container body-content">
  @RenderBody()
  <hr/>
  <footer>
    <p>&copy; 2016 - EmbeddedStock</p>
  </footer>
</div>

<environment names="Development">
  <script src="~/lib/jquery/dist/jquery.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
  <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.3.min.js"
          asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
          asp-fallback-test="window.jQuery">


  </script>
  <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
          asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
          asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">


  </script>
  <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@RenderSection("scripts", required: false)
</body>
</html>